### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by OrangeHoopla** [SpaghettiCoders/WellnessNetworkWebsite#8]
Refer so the google docs for what all the client wants on here. side note if we could include 
https://vincentgarreau.com/particles.js/
into the landing page i believe it would make the page more interactive

**Comment by OrangeHoopla** [comment]
@andrewghung I'm considering you in charge of the frontend so anyone that wants to work on this should go through you. Also we need to define our basic design etc

**Comment by OrangeHoopla** [comment]
Heres another good reference with what we should start with
https://startbootstrap.com/previews/agency/

**Comment by andrewghung** [comment]
Basic design layout complete. 
Decided on flat, warm aesthetic, similar to Headspace. 
Not designed responsively, will do if time permitting 
The particles.js looks nice to include, but it looks more appropriate for a tech website rather than a wellness podcast site. Arguably it's probably relaxing to do for users - consider adding it to the background sides of the page. 

**Backend attributes that I probably need stored to display dynamically:** 
Content Creator profiles

- Name (or if a speaker group, their group title) 
- Email (for admin view) 
- Phone number (probably optional) 
- Their personal speaker blurb. 
- Regular schedule time slot (for now, assuming the podcast is regular). 
- Profile picture 

Uploaded Podcasts

- Title of podcast
- Episode number
- Blurb of podcast
- Date aired
- Podcast cover 
- Duration
- Tags of who is in the podcast for sorting

**Comment by andrewghung** [comment]
Assets needed from Pamela: 
Her podcast cover art 
Clarification of what she wants for the YouTube integration, relevant copy 
Any other copy she wants on the landing page

**Comment by andrewghung** [comment]
https://at-the-wellness-network.webflow.io/
This is as far as I'm going to get for sprint 1. 
Has some interactions (mostly just there to show I can add them) 
I'm finding it difficult to design around having so little content.
